services:
  # redis:
  #   container_name: test-redis
  #   image: redis:alpine
  #   restart: unless-stopped
  #   command: /bin/sh -c "redis-server --requirepass $$REDIS_PASSWORD"
  #   env_file:
  #     - .env.local
  #   ports:
  #     - 6379:6379
  #   networks:
  #     - network0
  web:
    container_name: mapdraw-web
    build:
      context: ./
      dockerfile: Dockerfile
    working_dir: /app/mapdraw-web
    env_file:
      - ./.env.local
    ports:
      - "5005:5005"
      - "3000:3000"
    volumes:
      - ./:/app/
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - network0
  db:
    # image: postgis/postgis
    # platform: linux/amd64 
    image: imresamu/postgis:18-3.6.1-alpine3.22
    container_name: mapdraw-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: toor
      POSTGRES_DB: mapdraw
    restart: unless-stopped
    env_file:
      - ./.env.local
    ports: 
      - "5432:5432"
    volumes:
      - postgres-data:/data/db
    networks:
      - network0


volumes:
  postgres-data:


networks:
  network0:
    driver: bridge
