version: "3"
services:
  # redis:
  #   container_name: test-redis
  #   image: redis:alpine
  #   restart: unless-stopped
  #   command: /bin/sh -c "redis-server --requirepass $$REDIS_PASSWORD"
  #   env_file:
  #     - .env.local
  #   ports:
  #     - 6379:6379
  #   networks:
  #     - test-network
  test:
    container_name: test
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - ./.env.local
    ports:
      - "5005:5005"
      - "3000:3000"
    volumes:
      - ./:/app/
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - test-network
  # db:
  #   image: postgis/postgis
  #   container_name: testdb
  #   env_file:
  #     - ./.env.local
  #   ports: 
  #     - "5432:5432"
  #   volumes:
  #     - postgres-data:/data/db
  #   networks:
  #     - test-network


volumes:
  postgres-data:


networks:
  test-network:
    driver: bridge
